---
title: "IMDB Predictions"
author: "Peters"
date: "8/31/2020"
output: html_document
---

Data avaiable through kaggle at: https://www.kaggle.com/c/imdb495

Objective: Determine a model that will help us predict imdb scores.

```{r setup, include=FALSE}
library("tidyverse")
```

```{r}
(test <- read_csv("imdb495/IMDBTest.csv"))
(train <- read_csv("imdb495/IMDBTrain.csv"))
(exchange <- read_csv("imdb495/exchange_rates.csv"))

```

Summarize data

```{r}
summary(train)
```

Regression Imputation - Filling in missing values with the regression predicted values

Try to clean variables 16-20

```{r}
ggplot(data=train, mapping=aes(x=gross, y=imdb_score)) +
  geom_point()
with(train, cor(gross, imdb_score, use="complete.obs"))
```
























```{r}
pairs(~imdb_score+num_critic_for_reviews+duration+gross+num_voted_users+num_user_for_reviews+budget+title_year+aspect_ratio, data = train)

```


We notice some ridiculous budgets for our currency, so we will need to do some conversions.
```{r}
ggplot(data=train, mapping=aes(x=budget, y=imdb_score)) +
  geom_point()

train %>% filter(budget>1e9) %>% select(movie_title, country)
```


```{r}
ggplot(data=train, mapping=aes(x=budget, y=imdb_score)) +
  geom_point()

train %>% filter(budget>100000000, country=="USA") %>% select(movie_title, country)
```

```{r}
rating <- train %>%
  group_by(content_rating) %>%
  summarize(score = mean(imdb_score), n=n()) %>%
  arrange(-score)

rating
barplot(rating$score, names.arg = rating$content_rating)
```


```{r}
train %>%
  group_by(color) %>%
  summarize(score = mean(imdb_score), n=n()) %>%
  arrange(-score)

```

```{r}

dir <- train %>%
  group_by(director_name) %>%
  summarize(score = mean(imdb_score), n=n()) %>%
  arrange(-score) %>%
  filter(n > 1)

plot(dir$score)
```

